### ISSUE TITLE
IE 11 - Logout button has blue background

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1193]
I think this can be fixed by setting [this line](https://github.com/cfpb/hmda-platform-ui/blob/c159333a5ec52c57a85b9bba47a47d25f6c05521/src/common/Header.css#L125) to be 

```css
background: transparent;
```

Or by adding a new rule of

```css
.nav-primary > li > button {
  background: transparent;
}
```
